#!/usr/bin/with-contenv bash

# folders
mkdir -p \
    /metadata/ \
    /config/ \
    /audiobooks/ \
    /podcasts/

# permissions
chown -R abc:abc \
    /config \
    /metadata \
    /audiobooks \
    /podcasts

chown -R audiobookshelf:audiobookshelf \
    /config \
    /metadata \
    /audiobooks \
    /podcasts ||
      echo "audiobookshelf user not found"
