name: Build and Push v2

on:
  push:
    branches:
      - master

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout project
        uses: actions/checkout@v4

      - id: keydb
        uses: oz-elhassid/get-latest-release@master
        with:
          repository: advplyr/audiobookshelf
          and_filters: "prerelease: false, draft: false"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: docker_check
        run: |
          if docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.keydb.outputs.tag_name }} >/dev/null 2>&1; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Docker buildx action for release
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file ./.github/workflows/docker/Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.keydb.outputs.tag_name }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest \
          --build-arg GIT_TAG=${{ steps.keydb.outputs.tag_name }} \
          --push .

      - name: Run Docker buildx action for edge
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file ./.github/workflows/docker/Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:build-$(git rev-parse --short "$(git ls-remote https://github.com/advplyr/audiobookshelf.git HEAD | cut -f 1)") \
          --build-arg GIT_TAG=master \
          --push .
